<a href="https://colab.research.google.com/github/GameLooped/Practica-calificada-1/blob/main/practicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Resolver con numpy los siguientes casos:

In [ ]:
#Crea un vector de números enteros del 1 al 20.
import numpy as np
vector = np.arange(1, 21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#Crea una matriz de 3x3 con valores aleatorios entre 0 y 1.
matriz = np.random.rand(3, 3)
print(matriz)

[[0.06339827 0.26372424 0.24491961]
 [0.53502901 0.48232067 0.55957145]
 [0.11573711 0.85313904 0.69852608]]


In [ ]:
#Redimensiona una matriz de 4x4 a una matriz de 2x8.
matriz = np.random.rand(4, 4)
matriz_redimensionada = matriz.reshape(2, 8)
print(matriz_redimensionada)

[[0.3480351  0.52386265 0.92221516 0.34463798 0.20360751 0.5047224
  0.21364268 0.34561425]
 [0.12543518 0.99205463 0.30482421 0.87693605 0.43337379 0.10630325
  0.92475588 0.57396767]]


In [ ]:
#Crea un array de 10 números equidistantes entre 0 y 1.
array = np.linspace(0, 1, 10)
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#Concatena dos vectores vertical y horizontalmente. (concatenate)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
horizontal = np.concatenate((a, b))
print("Concatenación horizontal:")
print(horizontal)

ab = a.reshape(-1, 1)
ba = b.reshape(-1, 1)

vertical = np.concatenate((ab, ba), axis=0)
print("\nConcatenación vertical:")
print(vertical)

Concatenación horizontal:
[1 2 3 4 5 6]

Concatenación vertical:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


2. Resolver las siguientes operaciones:

In [ ]:
#Calcula la suma, resta, multiplicación y división de dos vectores.
suma = a + b
resta = a - b
multiplicacion = a * b
division = a / b
print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


In [ ]:
#Calcula la media, mediana y desviación estándar de un vector.
media = np.mean(a)
mediana = np.median(a)
desviacion = np.std(a)
print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion)

Media: 2.0
Mediana: 2.0
Desviación estándar: 0.816496580927726


In [ ]:
#Normaliza un vector dividiendo cada elemento por el valor máximo.
vector_normalizado = a / np.max(a)
print("Vector normalizado:")
print(vector_normalizado)

Vector normalizado:
[0.33333333 0.66666667 1.        ]


In [ ]:
#Encuentra el índice del valor máximo y mínimo en un vector.
maximo = np.argmax(a)
minimo = np.argmin(a)
print("Índice del valor máximo:", maximo)
print("Índice del valor mínimo:", minimo)

Índice del valor máximo: 2
Índice del valor mínimo: 0


In [ ]:
#Realiza una multiplicación matricial entre dos matrices 3x3.
matriz1 = np.random.rand(3, 3)
matriz2 = np.random.rand(3, 3)
multiplicacion = np.dot(a, b)
print("Matriz 1:")
print(a)
print("\nMatriz 2:")
print(b)
print("\nResultado de la multiplicación matricial:")
print(multiplicacion)

Matriz 1:
[1 2 3]

Matriz 2:
[4 5 6]

Resultado de la multiplicación matricial:
32


3. Resolver con numpy los siguientes casos:

In [ ]:
#Selecciona los elementos pares de un vector de números enteros.
vector1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
pares = vector1[vector1 % 2 == 0]
print(pares)

[ 2  4  6  8 10]


In [ ]:
#Filtra los valores mayores que 5 en un vector
vector2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mayores = vector2[vector2 > 5]
print(mayores)

[ 6  7  8  9 10]


In [ ]:
#Filtra los valores iguales a cero
vector3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
cero = vector3[vector3 == 0]
print(cero)

[0]


In [ ]:
#Filtra los valores negativos
vector4 = np.array([-1, 2, -3, 4, 5, 6, -7, 8, -9, 10])
negativos = vector4[vector4 < 0]
print(negativos)

[-1 -3 -7 -9]


In [ ]:
#Aplicar la media a los valores mayores de 50.
vector5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 50, 100, 56, 70])
mean = np.mean(vector5)
vector5[vector5 > 50] = mean
print(vector5)

[ 1  2  3  4  5  6  7  8  9 10 50 23 23 23]


4. Resolver con numpy los siguientes casos:

In [ ]:
#Crea un vector de 10 elementos y reemplaza todos los valores mayores que 5 con 0.
vector6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
vector6[vector6 > 5] = 0
print(vector6)

[1 2 3 4 5 0 0 0 0 0]


In [ ]:
#Combina dos vectores booleanos utilizando las operaciones & (AND) y | (OR).
vector7 = np.array([True, False, True, False, True])
vector8 = np.array([False, False, True, True, False])
and_result = vector7 & vector8
or_result = vector7 | vector8
print("AND:", and_result)
print("OR:", or_result)


AND: [False False  True False False]
OR: [ True False  True  True  True]


In [ ]:
#Cuenta la cantidad de valores en un vector que son múltiplos de 3.
vector9 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
multiplos = vector9[vector9 % 3 == 0]
print(multiplos)

[3 6 9]


In [ ]:
#Encuentra los índices de los elementos no nulos en un vector. (np.nonzero)
vector10 = np.array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])
indices = np.nonzero(vector10)
print(indices)

(array([0, 2, 4, 6, 8]),)


In [ ]:
#Comprueba si todos los elementos en un array son mayores que un valor específico digitado por el usuario.
vector11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

valor = float(input("Ingresa un valor para comparar: "))
resultado = np.all(vector11 > valor)
if resultado:
    print(f"Todos los elementos son mayores que {valor}.")
else:
    print(f"No todos los elementos son mayores que {valor}.")

Ingresa un valor para comparar: 0
Todos los elementos son mayores que 0.0.


5. Resolver con numpy los siguientes casos:

In [ ]:
#Calcula el cuadrado de cada elemento en un vector.
vector12 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
cuadrado = np.square(vector12)
print(cuadrado)

[  1   4   9  16  25  36  49  64  81 100]


In [ ]:
#Utiliza la función exponencial para elevar todos los elementos de un vector a la misma potencia.
vector13 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
potencia = np.exp(vector13)
print(potencia)

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [ ]:
#Encuentra los valores máximos y mínimos en cada fila de una matriz.
matriz14 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz:")
print(matriz14)
maximos = np.max(matriz14, axis=1)
minimos = np.min(matriz14, axis=1)
print("Máximos por fila:", maximos)
print("Mínimos por fila:", minimos)


Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Máximos por fila: [3 6 9]
Mínimos por fila: [1 4 7]


In [ ]:
#Aplica la función sin a todos los elementos de un vector y almacena los resultados en otro vector.
vector15 = np.array([0, 30, 45, 60, 90])
seno = np.sin(np.deg2rad(vector15))
print(seno)


[0.         0.5        0.70710678 0.8660254  1.        ]


In [ ]:
#Realiza la transpuesta de una matriz 3x4.
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
transpuesta = matriz.T
print("Matriz original:")
print(matriz)
print("Matriz transpuesta:")
print(transpuesta)


Matriz original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matriz transpuesta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


6. Crea un DataFrame con las siguientes columnas: 'Nombre', 'Edad', 'Ciudad'.
Añade al menos 10 registros.

In [ ]:
import pandas as pd
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Sofía', 'Juan', 'Laura', 'Diego', 'Elena', 'Miguel'],
    'Edad': [28, 34, 23, 45, 30, 27, 22, 36, 40, 31],
    'Ciudad': ['Huancayo', 'Lima', 'Huancayo', 'Arequipa', 'trujillo', 'La Merced', 'Chanchamayo', 'Mazamari', 'Tumbes', 'Satipo']
}
df = pd.DataFrame(data)
print(df)

   Nombre  Edad       Ciudad
0     Ana    28     Huancayo
1    Luis    34         Lima
2  Carlos    23     Huancayo
3   Marta    45     Arequipa
4   Sofía    30     trujillo
5    Juan    27    La Merced
6   Laura    22  Chanchamayo
7   Diego    36     Mazamari
8   Elena    40       Tumbes
9  Miguel    31       Satipo


In [ ]:
#Del DataFrame creado, filtra a las personas que tienen más de 25 años.
edad = df[df['Edad'] > 25]
print(edad)

   Nombre  Edad     Ciudad
0     Ana    28   Huancayo
1    Luis    34       Lima
3   Marta    45   Arequipa
4   Sofía    30   trujillo
5    Juan    27  La Merced
7   Diego    36   Mazamari
8   Elena    40     Tumbes
9  Miguel    31     Satipo


In [ ]:
#A tu DataFrame, añade una nueva columna llamada 'Ingresos', rellenala con cualquier valor.
df['Ingresos'] = [1000, 2000, 1500, 3000, 2500, 1800, 2200, 2800, 3200, 2700]
print(df)

   Nombre  Edad       Ciudad  Ingresos
0     Ana    28     Huancayo      1000
1    Luis    34         Lima      2000
2  Carlos    23     Huancayo      1500
3   Marta    45     Arequipa      3000
4   Sofía    30     trujillo      2500
5    Juan    27    La Merced      1800
6   Laura    22  Chanchamayo      2200
7   Diego    36     Mazamari      2800
8   Elena    40       Tumbes      3200
9  Miguel    31       Satipo      2700


In [ ]:
#Encuentra el promedio de la edad en tu DataFrame.
promedio_edad = df['Edad'].mean()
print(promedio_edad)

31.6


In [ ]:
#Cuenta cuántas veces aparece cada ciudad en tu DataFrame.
ciudad = df['Ciudad'].value_counts()
print(ciudad)

Ciudad
Huancayo       2
Lima           1
Arequipa       1
trujillo       1
La Merced      1
Chanchamayo    1
Mazamari       1
Tumbes         1
Satipo         1
Name: count, dtype: int64


In [ ]:
#Agrupa tu DataFrame por 'Ciudad' y calcula el promedio de 'Edad' para cada ciudad. (groupby)
promedio_ciudad = df.groupby('Ciudad')['Edad'].mean()
print(promedio_ciudad)

Ciudad
Arequipa       45.0
Chanchamayo    22.0
Huancayo       25.5
La Merced      27.0
Lima           34.0
Mazamari       36.0
Satipo         31.0
Tumbes         40.0
trujillo       30.0
Name: Edad, dtype: float64


In [ ]:
# Ordena tu DataFrame por 'Edad', de manera ascendente y luego descendente.
df_ascendente = df.sort_values(by='Edad')
df_descendente = df.sort_values(by='Edad', ascending=False)
print("Ordenado de manera ascendente:")
print(df_ascendente)
print("\nOrdenado de manera descendente:")
print(df_descendente)

Ordenado de manera ascendente:
   Nombre  Edad       Ciudad  Ingresos
6   Laura    22  Chanchamayo      2200
2  Carlos    23     Huancayo      1500
5    Juan    27    La Merced      1800
0     Ana    28     Huancayo      1000
4   Sofía    30     trujillo      2500
9  Miguel    31       Satipo      2700
1    Luis    34         Lima      2000
7   Diego    36     Mazamari      2800
8   Elena    40       Tumbes      3200
3   Marta    45     Arequipa      3000

Ordenado de manera descendente:
   Nombre  Edad       Ciudad  Ingresos
3   Marta    45     Arequipa      3000
8   Elena    40       Tumbes      3200
7   Diego    36     Mazamari      2800
1    Luis    34         Lima      2000
9  Miguel    31       Satipo      2700
4   Sofía    30     trujillo      2500
0     Ana    28     Huancayo      1000
5    Juan    27    La Merced      1800
2  Carlos    23     Huancayo      1500
6   Laura    22  Chanchamayo      2200


7. Del archivo adjunto realizar los siguientes filtros:

In [ ]:
df = pd.read_excel('/content/universidad.xlsx')
df = pd.DataFrame(df)
print(df)

   Num Control              Carrera  Semestre Inscripción  Id Persona
0     SeNeTe01  Lic. en nutriología         7  2015-05-20           1
1     JeViPi02         Ing. química         8  2015-05-02           2
2     MaFeNú03      Lic. en derecho         6  2015-05-09           3
3     WiVaLó04     Ing. en sistemas         2  2016-12-03           4
4     BaRiDe05     Ing. mecatrónica        10  2018-12-01           5
..         ...                  ...       ...         ...         ...
95    StPeRu96  Lic. en nutriología         2  2015-12-15          96
96    MaRaRí97      Lic. en derecho         7  2016-12-28          97
97    NiBrPa98     Ing. mecatrónica         8  2015-05-14          98
98    LiÁvSa99  Lic. en nutriología         4  2016-05-28          99
99   MoNaBr100     Ing. mecatrónica         2  2018-05-11         100

[100 rows x 5 columns]


In [ ]:
#Indicar cuantos son de la carrera de Ing. en sistemas
df[df['Carrera'] == 'Ing. en sistemas']

Num Control           Carrera  Semestre Inscripción  Id Persona
3     WiVaLó04  Ing. en sistemas         2  2016-12-03           4
9     BePaNa10  Ing. en sistemas         9  2018-05-15          10
21    ArLaOc22  Ing. en sistemas         1  2015-12-17          22
24    JaSoAy25  Ing. en sistemas         2  2018-05-21          25
26    DoAlVi27  Ing. en sistemas         4  2016-05-16          27
31    JuNúHi32  Ing. en sistemas         4  2016-05-22          32
45    TeLaKa46  Ing. en sistemas         4  2017-12-20          46
55    ViSaDu56  Ing. en sistemas         1  2017-12-22          56
73    LiToVe74  Ing. en sistemas         8  2015-12-12          74
82    FrViVa83  Ing. en sistemas         4  2016-12-12          83
89    LuÁvAl90  Ing. en sistemas         6  2017-12-19          90
91    FéVaRo92  Ing. en sistemas         6  2018-05-02          92
93    ArMuNi94  Ing. en sistemas        10  2015-05-07          94

In [ ]:
#Indicar cuantos son de la carrera de Ing. en derecho(Lic. en derecho)
df[df['Carrera'] == 'Lic. en derecho']

Num Control          Carrera  Semestre Inscripción  Id Persona
2     MaFeNú03  Lic. en derecho         6  2015-05-09           3
7     JaAgEs08  Lic. en derecho         7  2018-12-12           8
12    RaBeBu13  Lic. en derecho        10  2017-05-21          13
14    DeRuTr15  Lic. en derecho         8  2017-12-25          15
17    MaGaBe18  Lic. en derecho         1  2018-12-02          18
25    AsPoLa26  Lic. en derecho         6  2016-05-15          26
32    LiMáSa33  Lic. en derecho         5  2018-12-01          33
33    ÁlPrLi34  Lic. en derecho         2  2017-05-02          34
47    SeVaSa48  Lic. en derecho         6  2016-05-09          48
49    MoVaGa50  Lic. en derecho         7  2018-12-17          50
50    AdSaCa51  Lic. en derecho         3  2015-12-07          51
56    LaFeVe57  Lic. en derecho         7  2018-05-16          57
60    DiQuPa61  Lic. en derecho         9  2018-12-14          61
84    FéRiLa85  Lic. en derecho         4  2015-05-28          85
85    ClArVe86  Lic. en derecho         3  2017-05-09          86
88    GeLaVa89  Lic. en derecho         5  2015-05-25          89
96    MaRaRí97  Lic. en derecho         7  2016-12-28          97

In [ ]:
df['Inscripción'] = pd.to_datetime(df['Inscripción'])

df_2015 = df[df['Inscripción'].dt.year == 2015]

print(df_2015)

   Num Control              Carrera  Semestre Inscripción  Id Persona
0     SeNeTe01  Lic. en nutriología         7  2015-05-20           1
1     JeViPi02         Ing. química         8  2015-05-02           2
2     MaFeNú03      Lic. en derecho         6  2015-05-09           3
5     AlAlEs06         Ing. química         9  2015-12-18           6
8     ClHeAr09  Lic. en nutriología         4  2015-05-01           9
21    ArLaOc22     Ing. en sistemas         1  2015-12-17          22
27    AnLuLl28    Lic. en pedagogía         4  2015-12-13          28
30    BrCuOc31    Lic. en pedagogía         1  2015-05-06          31
37    KlFuVi38     Ing. mecatrónica         9  2015-05-06          38
44    GoRuSa45         Ing. química         8  2015-12-06          45
50    AdSaCa51      Lic. en derecho         3  2015-12-07          51
59    LiMeAc60  Lic. en nutriología         3  2015-05-06          60
65    PaViLa66         Ing. química         8  2015-05-24          66
73    LiToVe74     I

In [ ]:
#Indicar cuantos son del 1 y 2 semestre
df_semestre = df[df['Semestre'] == 1]
print(df_semestre)

   Num Control              Carrera  Semestre Inscripción  Id Persona
6     SaMeSe07     Ing. mecatrónica         1  2018-12-02           7
17    MaGaBe18      Lic. en derecho         1  2018-12-02          18
21    ArLaOc22     Ing. en sistemas         1  2015-12-17          22
30    BrCuOc31    Lic. en pedagogía         1  2015-05-06          31
48    EuPrVi49         Ing. química         1  2016-05-13          49
55    ViSaDu56     Ing. en sistemas         1  2017-12-22          56
63    TeAlVa64     Ing. mecatrónica         1  2017-12-23          64
69    LuAgPa70         Ing. química         1  2016-12-07          70
75    IsRoVa76    Lic. en pedagogía         1  2018-05-27          76
77    ArMeLa78         Ing. química         1  2017-05-22          78
92    OrVeTr93  Lic. en nutriología         1  2015-05-03          93
